/**
 *  Header of the legal move generator
 *  This class takes the board and decides all the valid moves for one player
 */

#ifndef LEGAL_MOVE_GENERATOR
#define LEGAL_MOVE_GENERATOR

#include <board.hpp>
#include <moves.hpp>
#include <array>
#include <vector>


class LegalMoveGenerator 
  {
    public:
    Board* board;

    /**
     *  Constructor
     */    
    LegalMoveGenerator(Board &board);

    /**
     *  Method to generate all possible moves given a board configuration
     *  for the white or black player
     *  @param turn (int) 0 for black's turn and 1 for white's turn
     */
    std::vector<Moves> generate(int turn);

    /**
     *  Method that converts coordinates generated by the piece to actual moves
     *  that can be made on the board. The difference is that this returns structs
     *  that encapsulate potential pieces that might be captured as a result of the
     *  suggested move.
     */
    std::vector<Move> convertToMove(std::vector<std::array<int,2>> pieceMoveSuggestions);

    /**
     *  Method to print all the available moves of the current board configurations
     *  Mainly used for debugging
     *  @param turn (int) 0 for black's turn and 1 for white's turn
     */
    void printMoves(int turn);    
};

#endif